---
- name: disable ipv6 all
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present

- sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present
- sysctl: name=net.ipv6.conf.lo.disable_ipv6 value=1 state=present

- name: try reduce swap
  sysctl: name=vm.swappiness value=10 state=present

- name: Reduce reclaiming memory
  sysctl: name=vm.vfs_cache_pressure value=50 state=present

- name: Enable syncookies
  sysctl: name=net.ipv4.tcp_syncookies value=1 state=present

- name: Disable System Request
  sysctl: name=kernel.sysrq value=0 state=present

- name: Disable Source routing
  sysctl: name=net.ipv4.conf.default.accept_source_route value=0 state=present

- name: Enable source route verification
  sysctl: name=net.ipv4.conf.default.rp_filter value=1 state=present

- name: Enable source route verification
  sysctl: name=net.ipv4.conf.all.send_redirects value=0 state=present

- sysctl: name=net.ipv4.conf.default.send_redirects value=0 state=present

- name: Ignore bogus errors
  sysctl: name=net.ipv4.icmp_ignore_bogus_error_responses value=0 state=present

- name: Increase allowed watchers
  sysctl: name=fs.inotify.max_user_watches value=32768 state=present
